### ISSUE TITLE
Error with docker-java, potential problems with jackson? 

### ISSUE THREAD

**Issue by rferreira** [kpelykh/docker-java#46]
Same problem happens with 0.8.1 and 0.8.2-SNAPSHOT

```
 DockerClient dc = new DockerClient("http://master:4243/");
        try {
            List<Image> images  = dc.getImages("nr-base");
            LOG.debug(images.toString());

        } catch (DockerException e) {
            e.printStackTrace();
        }
```

causes: 

```
Exception in thread "main" com.sun.jersey.api.client.ClientHandlerException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Created" (class com.kpelykh.docker.client.model.Image), not marked as ignorable (8 known properties: "size", "parentId", "created", "repository", "tag", "id", "repoTags", "virtualSize"])
 at [Source: com.sun.jersey.client.apache4.ApacheHttpClient4Handler$HttpClientResponseInputStream@79b84841; line: 1, column: 23] (through reference chain: com.kpelykh.docker.client.model.Image["Created"])
    at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:644)
    at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:604)
    at com.sun.jersey.api.client.WebResource.handle(WebResource.java:698)
    at com.sun.jersey.api.client.WebResource.access$300(WebResource.java:74)
    at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:514)
    at com.kpelykh.docker.client.DockerClient.getImages(DockerClient.java:276)
    at com.kpelykh.docker.client.DockerClient.getImages(DockerClient.java:263)
    at com.n.s.minion.services.ContainerService.run(ContainerService.java:99)
    at com.n.s.minion.cli.RunCommand.run(RunCommand.java:38)
    at com.n.s.minion.cli.RunCommand.run(RunCommand.java:17)
    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76)
    at io.dropwizard.cli.Cli.run(Cli.java:70)
    at io.dropwizard.Application.run(Application.java:72)
    at com.n.s.minion.Minion.main(Minion.java:30)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "Created" (class com.kpelykh.docker.client.model.Image), not marked as ignorable (8 known properties: "size", "parentId", "created", "repository", "tag", "id", "repoTags", "virtualSize"])
 at [Source: com.sun.jersey.client.apache4.ApacheHttpClient4Handler$HttpClientResponseInputStream@79b84841; line: 1, column: 23] (through reference chain: com.kpelykh.docker.client.model.Image["Created"])
    at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
    at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:671)
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:762)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1297)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1275)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:247)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
    at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1233)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:677)
    at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:764)
    at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634)
    ... 13 more

```

**Comment by alexec** [comment]
Fixed here:

https://github.com/alexec/docker-java/

**Comment by luismclglass** [comment]
@alexec How did you support fasterxml?

I have the same problem that @rferreira and I need to do a ugly stuff on all model classes:

```
@JsonProperty("XXXX")
@com.fasterxml.jackson.annotation.JsonProperty("XXXX")
```

It's works for me, but is really, really ugly.

**Comment by rferreira** [comment]
@alexec I tried your fork and the problem persists. To @luismclglass point, it seems to be related to fasterxml's jackson annotations.
